version: "3"

networks:
  web:
    external: true
  internal:
    external: false
 
services:
  recipes.wmk.io:
    restart: always
    build:
      context:  ./
      dockerfile: Dockerfile 
    volumes:
      - './data:/data'  
    labels:
      - traefik.backend=recipes.wmk.io
      - traefik.frontend.rule=Host:recipes.wmk.io
      - traefik.docker.network=web
      - traefik.port=7600
    networks:
      - internal
      - web